### ISSUE TITLE
作者你好 请问能否出一个后端部署的详细文档

### ISSUE THREAD

**Issue by D4CC4D** [hb0730/boot-admin#25]
RT，感谢作者分享代码

**Comment by hb0730** [comment]
这是我的预览环境docker部署文件
 - docker-compose.yml
```yml
version: "3"
services:
  app_server:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: boot_admin_app
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Shanghai -DSpring.profiles.active=hb0730 -Xms256m -Xmx512m"
    networks:
      - boot-admin-net
  web_server:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: boot_admin_web
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Shanghai -DSpring.profiles.active=hb0730 -Xms256m -Xmx512m"
    ports:
      - "9002:9002"
    depends_on:
      - depends_on
    networks:
      - boot-admin-net
  job_server:
    build:
      context: .
      dockerfile: job.Dockerfile
    container_name: boot_admin_job
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Shanghai -DSpring.profiles.active=hb0730 -Xms256m -Xmx512m"
    networks:
      - boot-admin-net      
  ui_server:
    build:
      context: .
      dockerfile: ui.Dockerfile
    container_name: boot_admin_ui
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8082:80"
    networks:
      - boot-admin-net
networks:
  boot-admin-net:
    driver: bridge
```
- app.Dockerfile
```Dockerfile
FROM eclipse-temurin:17-jre as builder
WORKDIR application
ARG JAR_FILE=app-*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:17-jre
WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
```
- job.Dockerfile
```Dockerfile
FROM eclipse-temurin:17-jre as builder
WORKDIR application
ARG JAR_FILE=job-*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:17-jre
WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
```
- ui.Dockerfile
```Dockerfile
FROM nginx:stable-alpine as production-stage

ADD dist.tar.gz /usr/share/nginx/html/
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

- web.Dockerfile
```Dockerfile
FROM eclipse-temurin:17-jre as builder
WORKDIR application
ARG JAR_FILE=web-*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:17-jre
WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
```

- nginx配置
```nginx
server {
  listen 80;
  listen [::]:80;
  server_name xxxx;

  client_max_body_size 1024m;

  location / {
    proxy_pass http://172.31.170.5:8082/;
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /pvs/ {
    proxy_pass http://172.31.170.5:9002/;
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Prefix /pvs;
  } 
}
```

**注意点**
- `dist.tar.tz` 需要进入前端项目dist目下进行`tar -zcvf dist.tar.gz *`
- `DSpring.profiles.active` 替换自己的环境

maven 构建只有进入项目目录`mvn clean -DskipTests=true package`

启动没有先后顺序，只有理清`web`,`app`等module的关系即可,把相关的[sql](https://github.com/hb0730/boot-admin/tree/v6.1/docs/sql)脚本导入到mysql即可
